apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: {{ .Values.name }}-container
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- if .Values.mariadb.enabled }}
            - name: DB_HOST
              value: {{ .Values.name }}-mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: DB_USERNAME
              value: {{ .Values.mariadb.username }}
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: MYSQL_PASSWORD
            - name: DB_SSL_ENABLED
              value: "false"
            - name: DB_SSL_CA
              value: ""
            - name: DB_SSL_CERT
              value: ""
            - name: DB_SSL_KEY
              value: ""
            - name: MYSQL_SSL_CA
              value: ""
            - name: MYSQL_SSL_CERT
              value: ""
            - name: MYSQL_SSL_KEY
              value: ""
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          volumeMounts:
            - name: app-var
              mountPath: /app/var
            - name: app-storage
              mountPath: /app/storage
            - name: app-storage-logs
              mountPath: /app/storage/logs
            - name: var-log
              mountPath: /var/log
            - name: tmp
              mountPath: /tmp
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
            - name: mysql-config-home
              mountPath: /root/.my.cnf
              subPath: my.cnf
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | default "/" }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 15 }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
          #readinessProbe:
          #  httpGet:
          #    path: {{ .Values.probes.readiness.path | default "/" }}
          #    port: 80
          #  initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 60 }}
          #  periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
          #  timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 5 }}
          #  failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 3 }}
          #  successThreshold: 1
      volumes:
        - name: app-var
          emptyDir: {}
        - name: app-storage
          emptyDir: {}
        - name: app-storage-logs
          emptyDir: {}
        - name: var-log
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: mysql-config
          configMap:
            name: {{ .Values.name }}-mysql-config
        - name: mysql-config-home
          configMap:
            name: {{ .Values.name }}-mysql-config
      {{- if .Values.secrets.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.secrets.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}

